add i-have-a-dream codelab
MITCodeIt/MITCodeIt.github.io pull request #3
Opened 2017-08-06 21:54 UTC by amyzhaang

2017-08-20 02:08 UTC, kelseyc18 requested changes

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +        <p>In this codelab, you&#39;ll learn about event handling and if-conditionals.</p>
Generally, I think it would be helpful to provide a summary of what the app does in the Overview section. So for this one, something along the lines of "In this codelab, you will create an app that plays speeches by Martin Luther King Jr. and Malcolm X."

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +          <li>Use Arrangement components.</li>
Use `Arrangement` components to organize other components like buttons and labels on the screen.

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +          <li>Use if-else blocks to control what your app does.</li>
Use **if-else blocks** to control what your app does in different situations.

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +      <google-codelab-step label="Code your app">
Play MLK's speech

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +            <li>Demonstrate your working app</li>
We want our checkoffs to be specific enough so that sidekicks know exactly what the app should be doing.

"Play the MLK speech when the user clicks on the picture of MLK."

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +            <li>Explain what the AlignHorizontal property of the screen component does</li>
`AlignHorizontal` or **AlignHorizontal**

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +          <li>Create more complex user interfaces.</li>
Play media using the `Player` component.

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +          </ul>
Adding some formatting to the key words in the Checkoff would be helpful :)

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +      <google-codelab-step label="Add code to pause MLK speech">
Pause MLK's speech

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +        <p>Go to <b>Blocks View</b>. Let's add the ability to pause the speech if it is already playing. To do this, we will use an if-else block.</p>
`if-else` block

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +          <p>Conditional statements are fundamental to programming. They allow the program to make decisions based on the current state of the program. Almost all "if" statements check the values of
Add title: Conditional statements using `if-else` blocks

"check the values of component properties"

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +      <google-codelab-step label="Add code to pause the other speech">
"One speech at a time"

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +        <p>Now, we want to ensure that both speeches will never play at the same time. If the MLK speech is playing and we click the Malcolm X button, we want the MLK speech to pause.</p>
If the Malcolm X speech is playing, and we click on the MLK button, we want Malcolm X to pause.

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +          <li>Code the Malcolm X button exactly like the MLK button. We want both buttons to behave the exact same way.</li>
Make the Malcolm X button play/pause Malcolm X's speech. Make sure the MLK speech pauses if Malcolm X's speech begins playing.

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +          <p>Try playing the two speeches. Can you pause a speech once it's playing? If a speech is playing, will clicking the other button pause that speech and start the other speech?</p>
Try playing and pausing the two speeches. Start MLK's speech. Before it ends, click on Malcolm X. What happens?

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +            <li>Demonstrate your working app</li>
Play MLK's speech and interrupt it with Malcolm X's speech.

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +            <li>Explain how you coded the Malcolm X button</li>
Explain how you made the Malcolm X button work.

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +            <li>Explain how the program knows a speech is playing</li>
Explain how the program knows whether or not a speech is playing

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +            <li>Name the different things that can happen when a Button is clicked</li>
I think we can remove this last bullet. Checkoffs shouldn't be too long :P

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +        <p>You have used App Inventor to create an app that can play two different speeches without overlap.</p>
You have used App Inventor to create an app that can play two different speeches!

2017-08-20 02:08 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +          <li>Use Arrangement components.</li>
Update checklist to be the same as the one in the overview.

2017-08-20 18:52 UTC, kelseyc18 requested changes

2017-08-20 18:52 UTC, kelseyc18 commented on appinventor/codelabs/i-have-a-dream/index.html
> +        <p>In this codelab, you&#39;ll learn about event handling and if-conditionals.</p>
Also, can you add a screenshot of the final app, please?

I'll make a note to add screenshots for the other codelabs, too.

2017-08-24 21:15 UTC, amyzhaang commented on appinventor/codelabs/i-have-a-dream/index.html
> +        <p>In this codelab, you&#39;ll learn about event handling and if-conditionals.</p>
yeah! i think that's a great idea. how about michelle obama and hillary clinton?

2017-08-27 14:47 UTC, kelseyc18 commented
Hmm I'm wondering if we could find any speeches by female STEM people.

http://teachersrightinghistory.org/wp-content/uploads/TRH-Historic-American-Women-Database-DIC-2016.pdf

I'll look into it.

Le jeu. 24 août 2017 à 14:15, amyzhaang <notifications@github.com> a écrit :

> *@amyzhaang* commented on this pull request.
> ------------------------------
>
> In appinventor/codelabs/i-have-a-dream/index.html
> <https://github.com/MITCodeIt/MITCodeIt.github.io/pull/3#discussion_r135132933>
> :
>
> > +  <link rel="import" href="../../elements/codelab.html">
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Code+Pro:400|Roboto:400,300,400italic,500,700|Roboto+Mono <https://fonts.googleapis.com/css?family=Source+Code+Pro:400%7CRoboto:400,300,400italic,500,700%7CRoboto+Mono>">
> +  <link rel="icon" href="../../elements/favicon.png">
> +  <style>
> +    body {
> +      font-family: "Roboto",sans-serif;
> +    }
> +  </style>
> +
> +</head>
> +<body unresolved class="fullbleed">
> +
> +  <google-codelab title="I Have A Dream Codelab" feedback-link="https://goo.gl/forms/9zDi1V3arg167lIY2">
> +
> +      <google-codelab-step label="Overview">
> +        <p>In this codelab, you&#39;ll learn about event handling and if-conditionals.</p>
>
> yeah! i think that's a great idea. how about michelle obama and hillary
> clinton?
>
> —
> You are receiving this because your review was requested.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/MITCodeIt/MITCodeIt.github.io/pull/3#discussion_r135132933>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIk2kEExuwZojRfhixODmrNs9PupCtzbks5sbefqgaJpZM4Ou2mu>
> .
>

2017-09-04 21:56 UTC, merged